=== AdmSko/website-2/xml/projekt.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">

	<xs:element name="wedkarstwo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="definition" type="definitionType"/>
				<xs:element name="history" type="historyType"/>
				<xs:element name="fish" type="fishType"/>
				<xs:element name="famous" type="famousType"/>
				<xs:element name="sources" type="sourcesType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
				<xs:complexType name="historyType">
					<xs:sequence>
						<xs:element name="period" type="periodType" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
						
				</xs:complexType>
				
		
				<xs:complexType name="fishType">
					<xs:sequence>
						<xs:element name="splitmethod" type="splitmethodType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
					
	
				<xs:complexType name="famousType">
					<xs:sequence>
						<xs:element name="person" type="moreinfoType" minOccurs="0" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
				
				
				<xs:complexType name="sourcesType">
					<xs:sequence>
					 <xs:element name="site" type="siteType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
				
		
				
		
	
	



	
				<xs:simpleType name ="definitionType">
					<xs:restriction base="longStringType">
						<xs:minLength value="15"/>
					</xs:restriction>
				</xs:simpleType>
	
	
				<xs:complexType name="periodType">
					<xs:sequence>
						<xs:element name="name" type="shortStringType" minOccurs="0" maxOccurs="unbounded" />
						<xs:element name="txt" type="longStringType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute type="shortStringType" name="point"/>
				</xs:complexType>
				
							
				
					
				<xs:complexType name="splitmethodType">
					<xs:sequence>
						<xs:element name="typefish" type="typefishType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute type="shortStringType" name="nr" use="required"/>
				</xs:complexType>


				<xs:complexType name="typefishType">
					<xs:sequence>
						<xs:element name="typename" type="typenameType" minOccurs="1" maxOccurs="unbounded"/>
						<xs:element name="treename" type="treenameType" minOccurs="1" maxOccurs="unbounded"/>             
						<xs:element name="avrsize" type="avrsizeType" minOccurs="1" maxOccurs="unbounded"/> 
						<xs:element name="size" type="sizeType" minOccurs="1" maxOccurs="unbounded"/>
						<xs:element name="both" type="bothType" minOccurs="1" maxOccurs="unbounded"/>
						<xs:element name="protection" type="longStringType" minOccurs="1" maxOccurs="unbounded"/> 
						<xs:element name="photo" type="adressType" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute ref="id"/>
				</xs:complexType>

			
		
				<xs:simpleType name="bothType">
						<xs:union memberTypes="avrsizeType sizeType"/>
				</xs:simpleType>

				<xs:simpleType name="sizeType">
					<xs:restriction base="shortStringType">
						<xs:enumeration value="maly"/>
						<xs:enumeration value="sredni"/>
						<xs:enumeration value="duzy"/>
					</xs:restriction>
				</xs:simpleType>
	
				<xs:simpleType name="avrsizeType">
					<xs:restriction base="xs:positiveInteger">
					<xs:minInclusive value="1" />
					<xs:maxInclusive value="200" />
					</xs:restriction>
				</xs:simpleType>
	
					
						
				<xs:complexType name="treenameType">
					<xs:sequence>
						<xs:element name="name" type="shortStringType" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="additionalname" type="additionalnameType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name ="num" type="shortStringType" use="optional"/>
				</xs:complexType>

				<xs:complexType name="additionalnameType">
					<xs:complexContent>
						<xs:extension base="treenameType">
							<xs:sequence>
								<xs:element name="scientificname" type="scientificnameType" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
							<xs:attribute name="lang" type="shortStringType" use="required"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>


				<xs:complexType name="scientificnameType">
					<xs:sequence>
					<xs:element name="sc" type="shortStringType"/>
					</xs:sequence>
					<xs:attributeGroup ref="fishatrybute"/>
				</xs:complexType>
	
				<xs:attributeGroup name="fishatrybute">
					<xs:attribute name="kindfish" type="kindType"/>
					<xs:attribute name="obligatory" />
				</xs:attributeGroup>
	
				<xs:attribute name="obligatory" default="no" >
					<xs:simpleType>
						<xs:restriction base="shortStringType">
							<xs:pattern value="yes|no"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
	
				<xs:simpleType name="kindType">
					<xs:restriction base= "xs:string">
						<xs:enumeration value="elfisho"/>
						<xs:enumeration value="fosh"/>
						<xs:enumeration value="fishner"/>
					</xs:restriction>
				</xs:simpleType>
							  
			
	
	
	
	
				<xs:complexType name="personType">
					<xs:sequence>
						<xs:element name="name" type="shortStringType" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="surname" type="shortStringType" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="country" type="shortStringType" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element name="moreinfo" type="moreinfoType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="nmbr" type="shortStringType" use="required"/>
				</xs:complexType>
	
				<xs:complexType name="moreinfoType">
					<xs:complexContent>
						<xs:extension base="personType">
							<xs:sequence>
								<xs:element name="photo" type="adressType" minOccurs="0" maxOccurs="unbounded"/>
								<xs:element name="link" type="adressType" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>		
				
				<xs:complexType name="siteType">
						<xs:sequence>
							<xs:element name="name" type="nameadressType" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="link" type="adressType" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					<xs:attribute ref="id"/>
				</xs:complexType>
				
				<xs:complexType name="adressType">
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="source" type="xs:anyURI" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
	
				<xs:simpleType name="nameadressType" >
								 <xs:list itemType="xs:string"/>
				</xs:simpleType>
		
				<xs:simpleType name="typenameType">
					<xs:restriction base="shortStringType">
						<xs:enumeration	value="Ryby tłuste"/>
						<xs:enumeration	value="Ryby średnio-tłuste"/>
						<xs:enumeration	value="Ryby chude"/>
						<xs:enumeration	value="Ryby morskie"/>
						<xs:enumeration	value="Ryby słodkowodne"/>
					</xs:restriction>
				</xs:simpleType>


				<xs:attribute name="id">
					<xs:simpleType>
						<xs:restriction base="xs:byte"/>
					</xs:simpleType>
				</xs:attribute>



				<xs:simpleType name="shortStringType">
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="35"/>
					</xs:restriction>
				</xs:simpleType>


				<xs:simpleType name="longStringType">
					<xs:restriction base="xs:string">
						<xs:maxLength value="630"/>
					</xs:restriction>
				</xs:simpleType>
				
				
				
				
				
			
			
		
</xs:schema>

=== AdmSko/website-2/xml/projekt.xml
<?xml version="1.0" encoding="utf-8"?>
<wedkarstwo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="projekt.xsd">
	<definition>Wędkarstwo, jest to rodzaj zajęcia rekreacyjnego, hobby oraz jednocześnie jest jednym z najstarszych sportów, polega na łowieniu ryb na wędkę.</definition>
	
	<history>
		<period point="First">
			<name>Początki</name>
			<txt>
				Wędkarstwo jako rozrywka, początkowo tylko najbogatszej części społeczeństwa, znane była od tysiącleci. Rzymski poeta Publiusz Owidiusz Naso w poemacie Halieutica (Sztuka rybołówstwa) opisał wędkarskie sposoby łowienia ryb różnych gatunków. W I wieku n.e. o wędkowaniu wspomina też w swoim epigramie Marcus Valerius Martialis, a Claudius Aelianus w swoim dziele De Animalium Natura również zawarł obszerne opisy metod wędkowania.
			</txt>
		</period> 
		
		<period point="Second">
			<name>Dawna Polska</name>
			<txt>
				Najpełniej ten rodzaj rekreacji na ziemiach polskich rozwinął się w zaborze austriackim, gdzie stosunki prawne w wielonarodowej monarchii były najbardziej liberalne. Ludność miejscowa łowiła ryby, ale traktowała to zajęcie wyłącznie utylitarnie, gdyż ryby stanowiły poważne uzupełnienie na ogół jarskiego jadłospisu uboższych mieszkańców. Sport wędkowy, jak ówcześni mówili, wzorowany był na tradycjach zachodnich spopularyzowanych przez ówczesne elity, z których do najbardziej znanych należeli hr. Alfred i Artur Potoccy.
			</txt>
		</period >
		
		<period point="Third">
			<name>XIX-wieczna Polska</name>
			<txt>
				Po wprowadzeniu na terenie Galicji i Lodomerii przepisów ustawy rybackiej indywidualne uprawianie wędkarstwa stało się utrudnione, głównie z powodu ustanowienia rewirów rybackich, dzierżawionych przez rozmaitych użytkowników. 13 lipca 1879 roku zostało powołane Krajowe Towarzystwo Rybackie, którego pierwszym prezesem został dr M. Nowicki, sprawujący funkcję do 30 października 1890 roku. Zaistniała więc naturalna potrzeba większej integracji uprawiających „wędkowanie rozrywkowe” i wspólna dzierżawa rewirów rybackich.
			</txt>
		</period>
		
		<period point="Fourth">
			<name>Po I Wojnie Światowej</name>
			<txt>
				I wojna światowa wywarła nader ujemny wpływ na stosunki gospodarcze w regionie przemyskim. Szczególnie ucierpiało rybołówstwo tak rzeczne, jak i stawowe. Zanik moralności i poczucia cudzej własności spowodował, że rybostan katastrofalnie się zmniejszył, gdyż łowił każdy, kto tylko chciał, bez żadnych kart lub zezwoleń, posługując się nawet dynamitem i granatami. Łowiono, nie bacząc ani na okresy ochronne tarła ani na zapisane w ustawie wymiary. Ponadto nieuczciwi handlarze, równocześnie dzierżawcy rewirów rybackich utworzywszy spółkę handlową, dyktowali ceny, jakie sami chcieli, osiągając minimalny zysk 200%.
			</txt>
		</period>
		
		<period point="Fifth">
			<name>Podczas okupacji</name>
			<txt>
				W latach okupacji 1939–1945 władze niemieckie nie rozwiązały organizacji rybackich i wędkarskich, uznając je za organizacje gospodarcze wyższej użyteczności. Naczelną organizacją był Związek Organizacji Rybackich. Drugi stopień tworzyły Okręgowe Towarzystwa Rybackie zorganizowane na wzór KTR-u. Wszystkie towarzystwa wędkarskie musiały być ich członkami. W r. 1941 siedzibą ZOR stał się Kraków. W czasie wojny na terenie Generalnej Guberni działało 38 towarzystw wędkarskich, w których zrzeszonych było 3033 członków.
			</txt>
		</period>
	</history>
	
	<fish> 
		<splitmethod nr="I">
			<typefish id="1">
				<typename>Ryby tłuste</typename>
					<treename num="uno">
						<name>Łosoś</name>
							<additionalname lang ="latin">
								<scientificname kindfish="fosh" obligatory="no">
									<sc>Salmo salar</sc>
								</scientificname>
							</additionalname>
					</treename>
				<avrsize>120</avrsize>
				<size>duzy</size>
				<both>duzy</both>
				<protection>1 października - 31 grudnia</protection>
				<photo source="ryba3.png"/>
			</typefish>
			
			<typefish id="2">
				<typename>Ryby średnio-tłuste</typename>
				<treename num="dos">
						<name>Pstrąg</name>
							<additionalname lang ="latin">
								<scientificname kindfish="elfisho" obligatory="no">
									<sc>Oncorhynchus mykiss</sc>
								</scientificname>
							</additionalname>
				</treename>
				<avrsize>40</avrsize>
				<size>sredni</size>
				<both>40</both>
				<protection>1 września - 31 stycznia</protection>
				<photo source="ryba4.png"/>
			</typefish>
			
			<typefish id="3">
				<typename>Ryby chude</typename>
				<treename num="tres">
						<name>Flądra</name>
							<additionalname lang ="latin">
								<scientificname kindfish="fishner" obligatory="no">	
									<sc>Platichthys flesus</sc>
								</scientificname>
							</additionalname>
				</treename>
				<avrsize>34</avrsize>
				<size>maly</size>
				<both>maly</both>
				<protection>1 lutego - 31 maja</protection>
				<photo source="ryba5.png"/>
			</typefish>
		</splitmethod>
		
		<splitmethod nr="II">
			<typefish id="1">
				<typename>Ryby morskie</typename>
				<treename num="uno">
						<name>Śledź</name>
							<additionalname lang ="latin">
								<scientificname kindfish="elfisho" obligatory="no">
									<sc>Clupea harengus</sc></scientificname>
							</additionalname>
				</treename>
				<avrsize>22</avrsize>
				<size>maly</size>
				<both>maly</both>
				<protection>4 czerwca - 31 sierpnia</protection>
				<photo source="ryba1.png"/>
			</typefish>
			
			<typefish id="2">
				<typename>Ryby słodkowodne</typename>
				<treename num="dos">
						<name>Karp</name>
						<additionalname lang ="latin">
							<scientificname kindfish="fosh" obligatory="no">
								<sc>Cyprinus carpio</sc>
							</scientificname>
						</additionalname>
				</treename>
				<avrsize>60</avrsize>
				<size>sredni</size>
				<both>60</both>
				<protection>Brak</protection>
				<photo source="ryba2.jpg"/>
			</typefish>
		</splitmethod>
	</fish>

	<famous>
		<person nmbr="1st">
			<name>Rick</name>
			<surname>Clunn</surname>
			<country>USA</country>
				<moreinfo nmbr="1st">
					<photo source="rick.jpg"></photo>
					<link source="https://en.wikipedia.org/wiki/Rick_Clunn"></link>
				</moreinfo>
		</person>
		
		<person nmbr="2nd">
			<name>Michael</name>
			<surname>Laconelli</surname>
			<country>USA</country>
			<moreinfo nmbr="2nd">
					<photo source="michael.jpg"></photo>
					<link source="https://en.wikipedia.org/wiki/Michael_Iaconelli"></link>
			</moreinfo>
		</person>
	</famous>
	
	<sources>
		<site id="1">
			<name>Wikipedia.org</name>
			<link source="https://www.wikipedia.org"></link>
		</site>

		<site id="2" >
			<name>Rybobranie.pl</name>
			<link source="http://www.rybobranie.pl"> </link>
		</site>
		
		<site id="3">
			<name>Wedkuje.pl</name>
			<link source="https://wedkuje.pl"></link>
		</site>
	</sources>
</wedkarstwo>
